spring.application.name=Mcp-client
server.port=8066

spring.ai.azure.openai.api-key=${API_KEY}
spring.ai.azure.openai.endpoint=${Endpoint}
spring.ai.azure.openai.chat.options.deployment-name=${deployment}
spring.ai.azure.openai.chat.options.temperature=0.7











